const DEFAULT_BUTTON_UNDERLAY_DEFAULT = "#984fa0";
const PRIMARY_BUTTON_UNDERLAY_DEFAULT = "#229a80";
const DEFAULT_BUTTON_TEXT_DEFAULT = "#f5f5f5";
const BLACK_DEFAULT = "#000000";
const WHITE_DEFAULT = "#ffffff";
const BACKGROUND_COLOR = "#808080";

export const colors = {
  DEFAULT_BUTTON_UNDERLAY_DEFAULT,
  DEFAULT_BUTTON_TEXT_DEFAULT,
  PRIMARY_BUTTON_UNDERLAY_DEFAULT,
  BLACK_DEFAULT,
  WHITE_DEFAULT,
  BACKGROUND_COLOR
};
